name = "ATP45"
uuid = "e618d77b-d0d4-44a4-84cd-7e2c5c764d14"
authors = ["tcarion <tristan.carion@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
WellKnownGeometry = "0f680547-7be7-4555-8820-bb198eeb646b"

[compat]
AbstractTrees = "0.4"
GeoInterface = "1.0"
LibGEOS = "0.7"
OrderedCollections = "0, 1"
Proj = "1"
RecipesBase = "1.2"
WellKnownGeometry = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
